@API_HostAddress = https://localhost:8080/api
// Users
// Single user
GET {{API_HostAddress}}/users/{id}
Accept: application/json

###

// All users
GET {{API_HostAddress}}/users/
Accept: application/json

###

// Update user
PUT {{API_HostAddress}}/users/{id}
Accept: application/json

###

// Delete user
DELETE {{API_HostAddress}}/users/{id}
Accept: application/json

###

// Check if user exists
GET {{API_HostAddress}}/users/exists/{id}
Accept: application/json

###

// User roles
// Single user role
GET {{API_HostAddress}}/userRoles/{id}
Accept: application/json

###

// All user roles
GET {{API_HostAddress}}/userRoles/
Accept: application/json

###

// Update user role
PUT {{API_HostAddress}}/userRoles/{id}
Accept: application/json

###

// Delete user role
DELETE {{API_HostAddress}}/userRoles/{id}
Accept: application/json

###

// Check if user role exists
GET {{API_HostAddress}}/userRoles/exists/{id}
Accept: application/json

###

// Expenses
// Single expense
GET {{API_HostAddress}}/expense/{id}
Accept: application/json

###

// All expenses
GET {{API_HostAddress}}/expense/
Accept: application/json

###

// Update expense
PUT {{API_HostAddress}}/expense/{id}
Accept: application/json

###

// Delete expense
DELETE {{API_HostAddress}}/expense/{id}
Accept: application/json

###

// Check if expense exists
GET {{API_HostAddress}}/expense/exists/{id}
Accept: application/json

###

// Expense categories
// Single expense category
GET {{API_HostAddress}}/expenseCategory/{id}
Accept: application/json

###

// All expence categories
GET {{API_HostAddress}}/expenseCategory/
Accept: application/json

###

// Update expense category
PUT {{API_HostAddress}}/expenseCategory/{id}
Accept: application/json

###

// Delete expense category
DELETE {{API_HostAddress}}/expenseCategory/{id}
Accept: application/json

###

// Check if expense category exists
GET {{API_HostAddress}}/expenseCategory/exists/{id}
Accept: application/json